### PR TITLE
Bump insights-loggers-ruby gem to 0.1.12

### PR DESCRIPTION
**Pull request by lpichler**
`+ manageiq-logger to 0.4.0`

### CODE REVIEW

**Comment by lpichler** [comment]
cc @lindgrenj6

**Comment by lindgrenj6** [comment]
Admittedly this repo should probably be archived - we are not using it anywhere anymore. It has also been completely removed from app-interface.

**Comment by lpichler** [comment]
> Admittedly this repo should probably be archived - we are not using it anywhere anymore. It has also been completely removed from app-interface.

yes, @syncrou maybe can you archive this repo ?

**Comment by lpichler** [comment]
yes I did this change only for completeness.

**Comment by syncrou** [comment]
@lindgrenj6 @lpichler should this be merged before I archive?  🐔 & 🥚 

I know we're not running the code, but once archived I don't believe we can merge PRs against the repo.

**Review by lindgrenj6 — APPROVED** [review]
Yeah good point - I'll approve/merge this then we can archive it. That way if we ever need to bring it back from the dead it won't have that bug.

**Pull request merged**
